### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/root/.aicli/offlinetoken.txt'

### ISSUE THREAD

**Issue by flyemsafe** [karmab/aicli#22]
Trying this on Fedora 36 with podman results in the below error:

alias
```
alias aicli='podman run --net host -it --rm -e AI_OFFLINETOKEN=$AI_OFFLINETOKEN -v $HOME/.aicli:/root/.aicli -v $PWD:/workdir quay.io/karmab/aicli'
```
Error

```
aicli list cluster
Traceback (most recent call last):
  File "/usr/bin/aicli", line 11, in <module>
    load_entry_point('aicli', 'console_scripts', 'aicli')()
  File "/root/aicli/ailib/cli.py", line 1042, in cli
    args.func(args)
  File "/root/aicli/ailib/cli.py", line 105, in list_cluster
    ai = AssistedClient(args.url, token=args.token, offlinetoken=args.offlinetoken, debug=args.debug)
  File "/root/aicli/ailib/__init__.py", line 64, in __init__
    with open(offlinetokenpath, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/root/.aicli/offlinetoken.txt'
```

**Comment by karmab** [comment]
can you try the following alias (to address selinux issues) ?
alias aicli='podman run --net host -it --rm -e AI_OFFLINETOKEN=$AI_OFFLINETOKEN -v $HOME/.aicli:/root/.aicli:Z -v $PWD:/workdir quay.io/karmab/aicli'

**Comment by flyemsafe** [comment]
Thanks, that was it. Adding that Z for selinux.
