### ISSUE TITLE
aicli create cluster with openshift_version=4.10 is considered as 4.1 and 4.10

### ISSUE THREAD

**Issue by vu3oim** [karmab/aicli#26]
Here is an extract of our cluster_parameters.yaml (partial content only is put here) =>

pull_secret: /home/admin/pull-secret.txt
additional_ntp_source: 192.18.147.40
high_availability_mode: Full
schedulable_masters: false
api_vip: 192.92.82.170
ingress_vip: 192.92.82.171
vip_dhcp_allocation: false
openshift_version: 4.10 **<== This the version we want to use**

When we do => 

**aicli create cluster mycluster --paramfile ./cluster_parameters.yaml**

Creating cluster mycluster
Traceback (most recent call last):
  File "/home/admin/.local/bin/aicli", line 11, in <module>
    sys.exit(cli())
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/cli.py", line 1098, in cli
    args.func(args)
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/cli.py", line 68, in create_cluster
    ai.create_cluster(args.cluster, overrides.copy())
  File "/home/admin/.local/lib/python3.6/site-packages/ailib/__init__.py", line 369, in create_cluster
    self.client.v2_register_cluster(new_cluster_params=cluster_params)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 4331, in v2_register_cluster
    (data) = self.v2_register_cluster_with_http_info(new_cluster_params, **kwargs)  # noqa: E501
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 4409, in v2_register_cluster_with_http_info
    collection_formats=collection_formats)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 373, in request
    body=body)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 275, in POST
    body=body)
  File "/home/admin/.local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
assisted_service_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 29 Jun 2022 16:43:09 GMT', 'Content-Length': '243'})
HTTP response body: {"code":"400","href":"","id":400,"kind":"Error","reason":"Openshift version 4.1 for CPU architecture x86_64 is not supported: The requested release image for version (4.1) and CPU architecture (x86_64) isn't specified in release images list"}

Its not considering openshift_version: 4.10.

tcpdump packet capture (from aicli to aisvc) shows this =>

.{"name": "mycluster", "high_availability_mode": "Full", **"openshift_version": "4.1"**, "base_dns_domain": "netact.nsn-rdnet.net", "cluster_network_cidr": "192.128.0.0/14", "service_network_cidr": "172.30.0.0/16", "api_vip": "192.92.82.170", "ingress_vip": "192.92.82.171", "pull_secret": "{\"auths\":{\"registry:5000\":{\"auth\":\"cweh45sdWEsdfasa34h==\",\"email\":\"admin@redhat.com\"}}}", "ssh_public_key": "ecdsa-sha2-nistp521 uBeRwq1OR/tQG0LzYRDq2qOQiMWUxBkhDzQxMUZJrfPqQETc6Bu7km39kF25059AkqOZPUJ6Bx5jRvVEGW2U65WNZR8BUCtvOhg7IQ== admin@test", "vip_dhcp_allocation": false, "user_managed_networking": false, "additional_ntp_source": "192.8.147.40", "hyperthreading": "all", "network_type": "OVNKubernetes", "schedulable_masters": false, "cpu_architecture": "x86_64"}

Next we tried with this (with double quotes) =>
openshift_version: "4.10"

With double quotes, it works correctly.

What is the reason for this?
Earlier we use 4.8 OCP version and we did not see this issue. Now with 4.10 seems like some handling is converting 4.10 to 4.1?

**Comment by karmab** [comment]
sadly this is due to yaml rendering 4.10 as 4.1
workaround at https://github.com/karmab/aicli/commit/efca77169a0a87b52c00ed4db2db0f5f2a8b354f
